"""Writes THIRD_PARTY_LICENSES.md from `cargo metadata` of porta's generated crate.

Almide generates the Rust crate porta is compiled from; run this against
that crate after a build, for the platforms porta ships on:

    cargo metadata --format-version 1 --locked \
      --filter-platform x86_64-unknown-linux-gnu --filter-platform aarch64-unknown-linux-gnu \
      --filter-platform aarch64-apple-darwin --manifest-path <generated>/Cargo.toml > meta.json
    python3 scripts/third_party_licenses.py meta.json > THIRD_PARTY_LICENSES.md

The list is what the resolver chose for that build; see docs/enterprise/
distribution.md for why it can differ between builds.
"""
import collections
import json
import sys

PERMISSIVE = {'MIT', 'Apache-2.0', 'Apache-2.0 WITH LLVM-exception', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC',
              'Unicode-3.0', 'Zlib', 'MIT-0', 'Unlicense', 'BSL-1.0', 'CDLA-Permissive-2.0'}


def terms(expression):
    cleaned = expression.replace('/', ' OR ').replace('(', ' ').replace(')', ' ')
    parts = [p.strip() for p in cleaned.replace(' AND ', ' OR ').split(' OR ')]
    return {p for p in parts if p}


def main():
    metadata = json.load(open(sys.argv[1]))
    resolved = {node['id'] for node in metadata['resolve']['nodes']}
    packages = sorted((p for p in metadata['packages'] if p['id'] in resolved and p['name'] != 'almide-out'),
                      key=lambda p: (p['name'], p['version']))
    counts = collections.Counter(p.get('license') or 'UNKNOWN' for p in packages)
    unknown = [p for p in packages if not p.get('license') or not terms(p['license']) & PERMISSIVE]
    print('# Third-party licenses\n')
    print('Rust crates compiled into the `porta` binary, as resolved for Linux (x86-64, arm64) and macOS (arm64).')
    print('Generated by `scripts/third_party_licenses.py`; each crate\'s full licence text is in its source')
    print('package on crates.io. Where a crate offers a choice, porta takes it under the permissive option')
    print('(MIT or Apache-2.0; BSD-3-Clause for crates also offered under GPL-2.0).\n')
    print('Not compiled in, but loaded at run time on Linux: the C library (glibc, LGPL-2.1+), dynamically')
    print('linked from the host or image. TLS is rustls; porta links no OpenSSL.')
    print('Almide, the compiler porta is written in, is not part of the binary beyond its generated code.\n')
    print('## Summary\n')
    print('| Licence expression | Crates |\n|---|---|')
    for expression, count in counts.most_common():
        print(f'| {expression} | {count} |')
    print(f'\n{len(packages)} crates. Without a permissive option: {len(unknown)}'
          + (' — ' + ', '.join(p['name'] for p in unknown) if unknown else '') + '.\n')
    print('## Crates\n')
    print('| Crate | Version | Licence | Source |\n|---|---|---|---|')
    for p in packages:
        print(f"| {p['name']} | {p['version']} | {p.get('license') or 'UNKNOWN'} | {p.get('repository') or ''} |")


if __name__ == '__main__':
    main()
